### ISSUE TITLE
Extension Totally Stopped Working

### ISSUE THREAD

**Issue by rick-rheo** [fcapano/Edit-This-Cookie#170]
It seems with a recent Chrome update (not sure which) has totally broken  Edit This Cookie.   See below. Currently I'm on Chrome Version 62.0.3202.89.  I uninstalled and re-installed the extension and it makes no difference.

![image](https://user-images.githubusercontent.com/26754458/32472149-f5d71e52-c315-11e7-882b-bcccb86ded96.png)

**Comment by rick-rheo** [comment]
Sometimes, it will show cookies for some other domain entirely. But that's rate. Most of the time it just says "No cookies here!"

**Comment by rick-rheo** [comment]
Here's an example of the wrong cookies being shown

![image](https://user-images.githubusercontent.com/26754458/32472529-f81345e0-c317-11e7-9988-d40a31bc5a1c.png)

**Comment by dncrews** [comment]
This is happening to me, as well. I am additionally getting this in the JS console:

```
Warning: a promise was rejected with a non-error: [object String]
    at g (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:11246)
    at i.n._warn (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:15804)
    at i._rejectCallback (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:45600)
    at Function.i.reject.i.rejected (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:41344)
    at chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:39:63684
    at i (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:72787)
    at i._settlePromiseFromHandler (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:46193)
    at i._settlePromise (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:46993)
    at i._settlePromise0 (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:47692)
    at i._settlePromises (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:49019)
    at o._drainQueue (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:2790)
    at o._drainQueues (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:2851)
    at drainQueues (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/h1.js:25:984)
    at <anonymous>
```

**Comment by dncrews** [comment]
This is happening for me, as well

**Comment by dncrews** [comment]
so @rick-rheo if you want to see the cookies, just put it as the first tab in your first window as a workaround for now.

**Comment by bayotop** [comment]
Originally reported at: https://github.com/fcapano/Edit-This-Cookie/issues/167
